FROM golang:1.23-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -trimpath -ldflags "-s -w" -o /app/main cmd/job/main.go

FROM alpine:3.12
ENV STORAGE_PATH=/app

RUN apk add --no-cache ca-certificates git tzdata

WORKDIR /app

COPY --from=builder /app/main /usr/local/bin/robomaster-diff-job
COPY entrypoint-cron.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

VOLUME /app

CMD ["/entrypoint.sh"]