name: Build

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: inject go-build-cache into docker
        # v1 was composed of two actions: "inject" and "extract".
        # v2 is unified to a single action.
        uses: reproducible-containers/buildkit-cache-dance@v2.1.2
        with:
          cache-source: go-build-cache

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Push
        uses: docker/build-push-action@v6
        if: github.event_name == 'push'
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.title=robomaster-diff
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Docker Push Job
        uses: docker/build-push-action@v6
        if: github.event_name == 'push'
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: Dockerfile-job
          tags: |
            ghcr.io/${{ github.repository }}/job:latest
            ghcr.io/${{ github.repository }}/job:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.title=robomaster-diff
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Docker Push Cron
        uses: docker/build-push-action@v6
        if: github.event_name == 'push'
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: Dockerfile-cron
          tags: |
            ghcr.io/${{ github.repository }}/cron:latest
            ghcr.io/${{ github.repository }}/cron:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.title=robomaster-diff
          cache-from: type=gha
          cache-to: type=gha,mode=max