name: Watch Job

permissions:
  contents: write

on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes
  workflow_dispatch:

jobs:
  task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: archive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Pull
        uses: docker/build-push-action@v6
        with:
          pull: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}/job:latest
            ghcr.io/${{ github.repository }}/job:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Job
        run: docker run -v ./:/app --rm ghcr.io/${{ github.repository }}/job:latest

      - name: Push Archive
        run: |
          git push
          
        
      
